# Generated by Django 3.2.23 on 2024-03-25 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='valor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='detallePaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPaquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.paquete')),
            ],
        ),
    ]
