# Generated by Django 3.2.23 on 2024-03-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240325_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepaquete',
            name='idServicio',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.servicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallepaquete',
            name='idPaquete',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.paquete'),
        ),
    ]
