# Generated by Django 4.2.11 on 2024-04-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_familiar_familiarpaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('noticia', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CentroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('blog', models.ManyToManyField(to='myapp.blognoticia')),
                ('medicos', models.ManyToManyField(to='myapp.medico')),
            ],
        ),
    ]
