# Generated by Django 4.2.11 on 2024-04-15 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blognoticia_centromedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('medicion', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='descripcion',
            new_name='umbral',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='paquete',
        ),
        migrations.AddField(
            model_name='servicio',
            name='detalleServicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.detalleservicio'),
        ),
    ]
