# Generated by Django 5.0.2 on 2024-06-11 03:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_pacientepaquete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientedispositivo',
            old_name='fechaModificación',
            new_name='fechaModificacion',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='alerta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='idPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.paciente'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(default='Default'),
        ),
        migrations.AddField(
            model_name='blognoticia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blognoticia',
            name='img',
            field=models.ImageField(default='blog1.jpg', upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='horaCita',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='color',
            field=models.CharField(default='Negro', max_length=150),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='imgD',
            field=models.ImageField(default='dispositivo1.jpg', upload_to='dispositivo_images/'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='modelo',
            field=models.CharField(default='Modelo por default', max_length=200),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='version',
            field=models.CharField(default='Version 1.0.0', max_length=250),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='receta',
            field=models.CharField(default='Consulte con su médico', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blognoticia',
            name='noticia',
            field=models.CharField(max_length=100000),
        ),
    ]
