# Generated by Django 5.0.2 on 2024-06-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_fechamodificación_pacientedispositivo_fechamodificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='img',
            field=models.ImageField(default='paq1.jpg', upload_to='paq_images/'),
        ),
    ]
