# Generated by Django 5.0.2 on 2024-06-18 20:04

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_paquete_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='indicaciones',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pacientepaquete',
            old_name='idDispositivo',
            new_name='dispositivo',
        ),
        migrations.RenameField(
            model_name='pacientepaquete',
            old_name='idPaciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='pacientepaquete',
            old_name='idPaquete',
            new_name='paquete',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='img',
        ),
        migrations.RemoveField(
            model_name='recetamedica',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='detalleServicio',
        ),
        migrations.AddField(
            model_name='detalleservicio',
            name='servicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='myapp.servicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='descripcion_detallada',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='detallereceta',
            name='dosis',
            field=models.CharField(default='Consulte con su médico', max_length=100),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='PacienteDetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.detalleservicio')),
                ('paciente_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='myapp.pacientepaquete')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=myapp.models.paquete_image_directory_path)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='myapp.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquete_servicios', to='myapp.paquete')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_paquetes', to='myapp.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='paquete',
            name='servicios',
            field=models.ManyToManyField(related_name='paquetes', through='myapp.PaqueteServicio', to='myapp.servicio'),
        ),
        migrations.DeleteModel(
            name='detallePaquete',
        ),
    ]
