# Generated by Django 4.2.11 on 2024-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_ciudad_remove_user_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
