# Generated by Django 4.2.11 on 2024-04-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_ciudad_user_direccion_user_estadocivil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='user.rol'),
        ),
    ]
